server:
  port: 32088
spring:
  datasource:
    url: jdbc:mysql://192.168.1.128:3306/Test_demo?useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
